version: "3"



services:



  app:

    container_name: Question_Generator_T5

    build: .

    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 5000 --reload"
    volumes:

      - .:/app

    ports:

      - 5000:5000
      